[package]
name = "radixdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
binary-merge = "0.1.2"
byte-slice-cast = "1.2.1"
hex = "0.4.3"
inplace-vec-builder = "0.1.1"
