[package]
name = "radixdb"
version = "0.1.0"
edition = "2021"
authors = ["Rüdiger Klaehn <rklaehn@protonmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
binary-merge = "0.1.2"
fnv = "1.0.7"
hex = "0.4.3"
inplace-vec-builder = "0.1.1"
lazy_static = "1.4.0"
log = "0.4.16"
parking_lot = "0.12.0"
thousands = "0.2.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
memmap = "0.7.0"

[dev-dependencies]
env_logger = "0.9.0"
log = "0.4.16"
obey = "0.1.0"
proptest = "1.0.0"
tempfile = "3.3.0"
thousands = "0.2.0"
