[package]
name = "radixdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
binary-merge = "0.1.2"
fnv = "1.0.7"
hex = "0.4.3"
inplace-vec-builder = "0.1.1"
lazy_static = "1.4.0"
memmap = "0.7.0"
parking_lot = "0.12.0"
thousands = "0.2.0"

[dev-dependencies]
obey = "0.1.0"
proptest = "1.0.0"
tempfile = "3.3.0"
thousands = "0.2.0"
